version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - TURSO_DATABASE_URL=file:/data/accio.db?cache=shared
      - TWITTER_BEARER_TOKEN=${TWITTER_BEARER_TOKEN}
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - INSTAGRAM_ACCESS_TOKEN=${INSTAGRAM_ACCESS_TOKEN}
    volumes:
      - ./data:/data
      - ./cache:/app/cache
    command: ["--web", "--use-database", "--seed-database"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Optional: Add a database UI for development
  adminer:
    image: adminer:latest
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=app
      - ADMINER_DESIGN=flat
    depends_on:
      - app
    restart: unless-stopped