apiVersion: apps/v1
kind: Deployment
metadata:
  name: accio
  labels:
    app: accio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accio
  template:
    metadata:
      labels:
        app: accio
    spec:
      containers:
      - name: accio
        image: accio:latest
        imagePullPolicy: IfNotPresent
        args: ["--web", "--use-database", "--seed-database"]
        ports:
        - containerPort: 8080
          name: http
        envFrom:
        - configMapRef:
            name: accio-config
        - secretRef:
            name: accio-secrets
        volumeMounts:
        - name: data-volume
          mountPath: /data
        - name: cache-volume
          mountPath: /app/cache
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: accio-data-pvc
      - name: cache-volume
        emptyDir: {}