apiVersion: v1
kind: Secret
metadata:
  name: accio-secrets
  labels:
    app: accio
type: Opaque
data:
  # These are placeholders. In a real environment, you would use base64-encoded values
  # or use a secret management solution like Kubernetes Secrets or HashiCorp Vault
  TWITTER_BEARER_TOKEN: ""  # base64 encoded value
  TWITCH_CLIENT_ID: ""      # base64 encoded value
  TWITCH_CLIENT_SECRET: ""  # base64 encoded value
  GITHUB_TOKEN: ""          # base64 encoded value
  INSTAGRAM_ACCESS_TOKEN: "" # base64 encoded value