apiVersion: v1
kind: Service
metadata:
  name: accio
  labels:
    app: accio
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: http
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: accio